spring:
  r2dbc:
    url: r2dbc:mysql://127.0.0.1:3306/foodtruck_mobile_noti?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: 1234
  jpa:
    show-sql: true

logging:
  level:
    org:
      springframework:
        r2dbc: DEBUG

